### PR TITLE
flex-scope, remove flet catch handler

### PR DESCRIPTION
**Pull request by fmnoise**

### CODE REVIEW

**Comment by nodename** [comment]
Hi, I have an issue whose solution may conflict with this PR. It's about clojurescript support.
Please review my thoughts:
Since flet is a macro, it must be compiled by clj regardless of whether the target is clj or cljs.
Therefore the #?(:cljs) conditionals will not produce the desired expansions for cljs.
Therefore there must be a separate source file for each of the two.
So it's best to remove flet from the flow.cljc file.

In order to make the cljs version work I found it necessary to explicitly pass two arguments to the
cljs version of flet: the caught and the ?err, because at compilation time their cljs versions are not available. 
So in my user code I write `(flet #?(:cljs caught) #?(:cljs ?err)`.
I have been using it this way at work for several months and flet works both in clj and cljs.
I hope there's a way to not have to pass the two args but I can't come up with it myself.

My fork of flow is at [nodename/flow](https://github.com/nodename/flow).

**Comment by IGJoshua** [comment]
Something to consider for this as well is that the library [macrovich](https://github.com/cgrand/macrovich) provides macros to allow you to have proper "reader conditionals" which correctly identify jvm clojure macroexpanding cljs code as cljs. This may ease implementation for any macros which need different behavior across targets.

**Comment by fmnoise** [comment]
@nodename  I don't think this PR will be merged any time soon, it's more like working draft to try idea of catching scope within `flet` and I can't say I still like that idea, except maybe removing `:catch-handler` and optimizing `flet` which is breaking change as well. I definitely support having normally working flet for cljs (despite I don't use it there), so I'll check out your implementation for that. 
@IGJoshua macrovich is 👍🏽  gonna look into it

**Comment by fmnoise** [comment]
@nodename I reworked `flet` using `macrovich`, let me know if cljs version works for you now (maybe I misunderstood macrovich/case)

**Comment by fmnoise** [comment]
I had no luck with macrovich for `flet` so moved cljs macro to separate file `fmnoise.flow.macros`. 
It still doesn't work in cljs as expected though, doesn't return any errors but evaluates to nil.
Instead of passing `?err` and `caught` as args, I tried referring to it using fully qualified name, not sure if it works correctly though.
clj version left in place with reader macro and I'd not like to move it elsewhere as it will break all my production usage.
If you guys have any idea why `flet` in cljs is always evaluated to nil and how to fix it, any suggestions are welcome 🙏🏽 
Otherwise I'd leave it for clj only as I see cljs usage as experimental anyways.

**Pull request closed without merging**
